name: Deploy to WordPress.org
on:
  push:
    tags:
    - "*"
jobs:
  tag:
    name: New tag
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install PHP dependencies
      run: composer install
    - name: WordPress Plugin Deploy
      uses: 10up/action-wordpress-plugin-deploy@master
      env:
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
    - name: Notify Slack
      run: |
        tag=$(git describe --tags `git rev-list --tags --max-count=1`)
        curl -X POST --data-urlencode "payload={\"channel\": \"#slim-seo\", \"username\": \"Bot\", \"text\": \"New version $tag for Slim SEO has been just released!\", \"icon_emoji\": \":tada:\"}" ${{ secrets.SLACK_WEBHOOK }}
